const ADD_FAVS = "ADD_FAVS";
const DELETE_FAVS ='DELETE_FAVS';
const ORDER = "ORDER";
const FILTER = "FILTER";
const MOSTRAR = "MOSTRAR";
const GUARDARID = "GUARDARID";
const GUARDALOCATIONS= "GUARDALOCATIONS"


module.exports = {
    ADD_FAVS,
    DELETE_FAVS,  
    ORDER,
    FILTER,
    MOSTRAR,
    GUARDARID,
    GUARDALOCATIONS

  }